name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        run: msbuild ./WebApplication1/WebApplication1.sln /p:Configuration=Release
  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        run: msbuild ./WebApplication1/WebApplication1.sln /p:Configuration=Release
        
      - name: Run tests (replace with actual test commands)
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        run: msbuild ./WebApplication1/WebApplication1.sln /p:Configuration=Release

      - name: Deploy to staging (replace with actual deployment steps)
        run: echo "Deploying to staging..."

notify:
    needs: [build, test, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          status: 'failure'
          text: 'A build or deployment failed in the CI/CD pipeline.'
          author_name: 'GitHub Actions'
          color: '#FF0000'  # Red color
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}